version: '2'
services:
  business_lookup:
    build: .
    depends_on:
     - db
    volumes:
     - .:/usr/src/app
    environment:
     - USER=root
     - ENV=/usr/local
     - DBPASS=stompy
     - DBSRV=db
  db:
    env_file: .env
    image: 'quay.io/freshbooks/test-database:${TEST_DATABASE_VERSION}'
